### ISSUE TITLE
QSIGN服务不稳定

### ISSUE THREAD

**Issue by XokoukioX** [CikeyQi/QQsign_docs#14]
### **服务好像不是很稳定 以下是mirai端的输出(重启mirai是有效的 但是专挑我出门的时间坏掉 有点闹心)**
```
2024-01-17 00:39:14 E/UnidbgFetchQsign: xyz.cssxsh.mirai.tool.KFCStateException: unidbg-fetch-qsign 服务异常, 请检查其日志, 'QSign not initialized, unable to request_token, please submit the initialization package first.'
xyz.cssxsh.mirai.tool.KFCStateException: unidbg-fetch-qsign 服务异常, 请检查其日志, 'QSign not initialized, unable to request_token, please submit the initialization package first.'
	at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.check(UnidbgFetchQsign.kt:109)
	at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.requestToken(UnidbgFetchQsign.kt:204)
	at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.access$requestToken(UnidbgFetchQsign.kt:16)
	at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign$qSecurityGetSign$1.invokeSuspend(UnidbgFetchQsign.kt:160)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2024-01-17 01:00:01 I/blue-archive-arona: Source: STUDENT from GitHub already up to date.
2024-01-17 01:00:02 I/blue-archive-arona: Source: LOCALIZATION from GitHub already up to date.
2024-01-17 01:00:03 I/blue-archive-arona: Source: RAID from GitHub added.
2024-01-17 01:00:04 W/blue-archive-arona: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
2024-01-17 01:00:04 W/blue-archive-arona: 数据同步失败，无法保证数据准确性
2024-01-17 01:19:14 E/UnidbgFetchQsign: xyz.cssxsh.mirai.tool.KFCStateException: unidbg-fetch-qsign 服务异常, 请检查其日志, 'QSign not initialized, unable to request_token, please submit the initialization package first.'
xyz.cssxsh.mirai.tool.KFCStateException: unidbg-fetch-qsign 服务异常, 请检查其日志, 'QSign not initialized, unable to request_token, please submit the initialization package first.'
	at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.check(UnidbgFetchQsign.kt:109)
	at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.requestToken(UnidbgFetchQsign.kt:204)
	at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.access$requestToken(UnidbgFetchQsign.kt:16)
	at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign$qSecurityGetSign$1.invokeSuspend(UnidbgFetchQsign.kt:160)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2024-01-17 01:59:14 E/UnidbgFetchQsign: xyz.cssxsh.mirai.tool.KFCStateException: unidbg-fetch-qsign 服务异常, 请检查其日志, 'QSign not initialized, unable to request_token, please submit the initialization package first.'
xyz.cssxsh.mirai.tool.KFCStateException: unidbg-fetch-qsign 服务异常, 请检查其日志, 'QSign not initialized, unable to request_token, please submit the initialization package first.'
	at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.check(UnidbgFetchQsign.kt:109)
	at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.requestToken(UnidbgFetchQsign.kt:204)
	at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.access$requestToken(UnidbgFetchQsign.kt:16)
	at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign$qSecurityGetSign$1.invokeSuspend(UnidbgFetchQsign.kt:160)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2024-01-17 02:00:01 I/blue-archive-arona: Source: STUDENT from GitHub already up to date.
```

**附件是QSIGN在Koyeb上面的日志（时间不对是因为没有找到最近的mirai日志 但是mirai的报错内容是一样的）**
[qsign-unidbg-fetch-qsign-docker.txt](https://github.com/CikeyQi/QQsign_docs/files/14072899/qsign-unidbg-fetch-qsign-docker.txt)

**Comment by CikeyQi** [comment]
根据提供的日志没有找到什么问题（或者说我看不出来问题出在哪），异常之后Koyeb的控制台显示异常还是显示服务正常运行，我想我需要异常发生后程序退出前的相关日志

**Comment by XokoukioX** [comment]
麻烦了
[整理后的日志.txt](https://github.com/CikeyQi/QQsign_docs/files/14100001/default.txt)
koyeb服务会自动重启 这次的日式应该包含了错误

**Comment by XokoukioX** [comment]
> 可以尝试 [这里的文件](https://github.com/luanyaolingwu/luanyaolingwu.github.io/releases/download/FqlQSign1.1.9-Original/) ，解压jar出来，把启动命令改成 java -jar xxxx.jar --basePath= 不一定保证稳定 备注: 不支持8996以上版本 [抱脸的临时测试网址](https://qsignluoyu-free.hf.space/status)

仓库已经404了诶
